In [1]:
def check_even_odd(number):
    if number % 2 == 0:
        return f"{number} is even"
    else:
        return f"{number} is odd"

# Test the function
num = 7
print(check_even_odd(num))

7 is odd


In [3]:
for i in range(1, 11):
    print(i, end=" ")

1 2 3 4 5 6 7 8 9 10 

In [5]:
def factorial(n):
    result = 1
    i = 1
    while i <= n:
        result *= i
        i += 1
    return result

# Test the function
n = 5
print(f"Factorial of {n} is {factorial(n)}")

Factorial of 5 is 120


In [7]:
def find_maximum(a, b, c):
    if a >= b and a >= c:
        return a
    elif b >= a and b >= c:
        return b
    else:
        return c

# Test the function
a, b, c = 10, 25, 15
print(f"Maximum of {a}, {b}, and {c} is {find_maximum(a, b, c)}")

Maximum of 10, 25, and 15 is 25


In [9]:
def fibonacci(n):
    fib_series = [0, 1]
    for i in range(2, n):
        fib_series.append(fib_series[i-1] + fib_series[i-2])
    return fib_series

# Get first 10 Fibonacci numbers
fib = fibonacci(10)
print("First 10 Fibonacci numbers:", fib)

First 10 Fibonacci numbers: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [11]:
def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True

# Test the function
num = 17
print(f"{num} is {'prime' if is_prime(num) else 'not prime'}")

17 is prime


In [13]:
even_numbers = []
for i in range(1, 101):
    if i % 2 == 0:
        even_numbers.append(i)

print("Even numbers from 1 to 100:", even_numbers)

Even numbers from 1 to 100: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [15]:
def sum_to_n(n):
    total = 0
    i = 1
    while i <= n:
        total += i
        i += 1
    return total

# Test the function
n = 100
print(f"Sum of numbers from 1 to {n} is {sum_to_n(n)}")

Sum of numbers from 1 to 100 is 5050


In [17]:
def reverse_string(input_str):
    reversed_str = ""
    for char in input_str:
        reversed_str = char + reversed_str
    return reversed_str

# Test the function
text = "Hello, World!"
print(f"Original: {text}")
print(f"Reversed: {reverse_string(text)}")

Original: Hello, World!
Reversed: !dlroW ,olleH


In [19]:
def filter_positive(numbers):
    return [num for num in numbers if num > 0]

# Test the function
numbers = [-5, 10, -7, 0, 15, -3, 8]
print("Original list:", numbers)
print("Positive numbers:", filter_positive(numbers))

Original list: [-5, 10, -7, 0, 15, -3, 8]
Positive numbers: [10, 15, 8]


In [21]:
import pandas as pd

# Sample dictionary
data = {
    'Name': ['John', 'Alice', 'Bob', 'Emily'],
    'Age': [25, 30, 22, 28],
    'City': ['New York', 'London', 'Paris', 'Tokyo']
}

# Create DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

    Name  Age      City
0   John   25  New York
1  Alice   30    London
2    Bob   22     Paris
3  Emily   28     Tokyo


In [23]:
import numpy as np

# Create a NumPy array
arr = np.array([10, 15, 20, 25, 30])

# Calculate mean
mean_value = np.mean(arr)

print("Array:", arr)
print("Mean:", mean_value)

Array: [10 15 20 25 30]
Mean: 20.0


In [25]:
import numpy as np

# Create two NumPy arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

# Multiply arrays element-wise
result = arr1 * arr2

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Element-wise multiplication:", result)

Array 1: [1 2 3 4 5]
Array 2: [5 4 3 2 1]
Element-wise multiplication: [5 8 9 8 5]


In [27]:
import pandas as pd

# Create a sample DataFrame
data = {
    'A': [10, 20, 30, 40, 50],
    'B': [15, 25, 35, 45, 55],
    'C': [5, 10, 15, 20, 25]
}

df = pd.DataFrame(data)

# Calculate sum of column 'A'
column_sum = df['A'].sum()

print("DataFrame:")
print(df)
print(f"Sum of column 'A': {column_sum}")

DataFrame:
    A   B   C
0  10  15   5
1  20  25  10
2  30  35  15
3  40  45  20
4  50  55  25
Sum of column 'A': 150


In [29]:
import pandas as pd

# Create a sample DataFrame
data = {
    'ID': [1, 2, 3, 4, 5],
    'Value': [15, 32, 8, 47, 23]
}

df = pd.DataFrame(data)

# Set threshold
threshold = 20

# Filter rows
filtered_df = df[df['Value'] > threshold]

print("Original DataFrame:")
print(df)
print(f"\nRows where Value > {threshold}:")
print(filtered_df)

Original DataFrame:
   ID  Value
0   1     15
1   2     32
2   3      8
3   4     47
4   5     23

Rows where Value > 20:
   ID  Value
1   2     32
3   4     47
4   5     23


In [31]:
import pandas as pd
import numpy as np

# Create DataFrame with missing values
data = {
    'A': [10, 20, np.nan, 40, 50],
    'B': [np.nan, 25, 35, np.nan, 55],
    'C': [5, np.nan, 15, 20, np.nan]
}

df = pd.DataFrame(data)

# Replace missing values with column mean
df_filled = df.fillna(df.mean())

print("Original DataFrame with NaN values:")
print(df)
print("\nDataFrame with NaN replaced by column mean:")
print(df_filled)

Original DataFrame with NaN values:
      A     B     C
0  10.0   NaN   5.0
1  20.0  25.0   NaN
2   NaN  35.0  15.0
3  40.0   NaN  20.0
4  50.0  55.0   NaN

DataFrame with NaN replaced by column mean:
      A          B          C
0  10.0  38.333333   5.000000
1  20.0  25.000000  13.333333
2  30.0  35.000000  15.000000
3  40.0  38.333333  20.000000
4  50.0  55.000000  13.333333


In [33]:
import pandas as pd

# Create a sample DataFrame
data = {
    'A': [10, 20, 30, 40],
    'B': [15, 25, 35, 45],
    'C': [5, 10, 15, 20]
}

df = pd.DataFrame(data)

# Convert to NumPy array
np_array = df.to_numpy()

print("DataFrame:")
print(df)
print("\nNumPy Array:")
print(np_array)

DataFrame:
    A   B   C
0  10  15   5
1  20  25  10
2  30  35  15
3  40  45  20

NumPy Array:
[[10 15  5]
 [20 25 10]
 [30 35 15]
 [40 45 20]]


In [35]:
import pandas as pd

# Create a sample DataFrame
data = {
    'Name': ['John', 'Alice', 'Bob', 'Emily'],
    'Age': [25, 30, 22, 28],
    'Score': [85, 92, 78, 95]
}

df = pd.DataFrame(data)

# Sort by 'Score' column in ascending order
sorted_df = df.sort_values(by='Score')

print("Original DataFrame:")
print(df)
print("\nSorted DataFrame (by Score, ascending):")
print(sorted_df)

Original DataFrame:
    Name  Age  Score
0   John   25     85
1  Alice   30     92
2    Bob   22     78
3  Emily   28     95

Sorted DataFrame (by Score, ascending):
    Name  Age  Score
2    Bob   22     78
0   John   25     85
1  Alice   30     92
3  Emily   28     95


In [37]:
import numpy as np

# Create a 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate sum along axis 0 (columns)
sum_axis0 = np.sum(arr, axis=0)

# Calculate sum along axis 1 (rows)
sum_axis1 = np.sum(arr, axis=1)

print("Original 2D array:")
print(arr)
print("\nSum along axis 0 (columns):")
print(sum_axis0)
print("\nSum along axis 1 (rows):")
print(sum_axis1)

Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum along axis 0 (columns):
[12 15 18]

Sum along axis 1 (rows):
[ 6 15 24]


In [39]:
import pandas as pd

# Create DataFrame with duplicate rows
data = {
    'A': [1, 2, 3, 2, 1],
    'B': [10, 20, 30, 20, 10],
    'C': ['a', 'b', 'c', 'b', 'a']
}

df = pd.DataFrame(data)

# Drop duplicate rows
df_no_duplicates = df.drop_duplicates()

print("Original DataFrame:")
print(df)
print("\nDataFrame with duplicates removed:")
print(df_no_duplicates)

Original DataFrame:
   A   B  C
0  1  10  a
1  2  20  b
2  3  30  c
3  2  20  b
4  1  10  a

DataFrame with duplicates removed:
   A   B  C
0  1  10  a
1  2  20  b
2  3  30  c
